from typing import Any, Optional, Union

from scalecodec.base import ScaleType, ScaleDecoder
from scalecodec._scale_bytes import ScaleBytes

class Struct(ScaleType[dict[str, Any]]): ...
class Enum(ScaleType[dict[str, Any]]): ...
class Tuple(ScaleType[tuple[Any, ...]]): ...
class Set(ScaleType[dict[str, Any]]): ...
class Vec(ScaleType[list[Any]]): ...
class Option(ScaleType[Optional[Any]]): ...
class Bytes(ScaleType[str]): ...
class String(ScaleType[str]): ...
class Bool(ScaleType[bool]): ...
class Compact(ScaleType[int]): ...
class H256(ScaleType[str]): ...
class H160(ScaleType[str]): ...
class U8(ScaleType[int]): ...
class U16(ScaleType[int]): ...
class U32(ScaleType[int]): ...
class U64(ScaleType[int]): ...
class U128(ScaleType[int]): ...
class U256(ScaleType[int]): ...
class I8(ScaleType[int]): ...
class I16(ScaleType[int]): ...
class I32(ScaleType[int]): ...
class I64(ScaleType[int]): ...
class I128(ScaleType[int]): ...
class FixedLengthArray(ScaleType[Any]): ...
class GenericAccountId(H256): ...
class GenericBlock(ScaleType[dict[str, Any]]): ...
class GenericCall(ScaleType[dict[str, Any]]): ...
class GenericExtrinsic(ScaleType[dict[str, Any]]): ...
class GenericEvent(Enum): ...
class GenericMultiAddress(Enum): ...
class GenericPalletMetadata(Struct): ...
class ScaleInfoPalletMetadata(GenericPalletMetadata): ...
class GenericStorageEntryMetadata(Struct): ...
class GenericRegistryType(Struct): ...
class GenericMetadataAll(Enum): ...

class GenericMetadataVersioned(Tuple):
    def __getitem__(self, item: Any) -> Any: ...
    @property
    def portable_registry(self) -> Optional[Any]: ...
    @property
    def pallets(self) -> list[GenericPalletMetadata]: ...
    def get_metadata(self) -> GenericMetadataAll: ...
    def get_metadata_pallet(self, name: str) -> GenericPalletMetadata: ...
    def get_pallet_by_index(self, index: int) -> GenericPalletMetadata: ...
    def get_signed_extensions(self) -> dict[str, dict[str, Optional[str]]]: ...
    @property
    def call_index(self) -> Any: ...
    @property
    def event_index(self) -> Any: ...
    def get_module_error(self, module_index: int, error_index: int) -> Any: ...
